Testing

In [1]:
from BruteForcePermutation import *
import numpy as np
from random import *

# chose these values for better testing:
cost_of_x = 1
cost_of_cx = 10
cost_of_ccx = 40

In [ ]:
ket0 = np.matrix([[1],[0]])

ket1 = np.matrix([[0],[1]])

I = np.matrix([[1,0],[0,1]])

X = np.matrix([[0,1],[1,0]])

ketbra0 = np.matrix([[1,0],[0,0]])

ketbra1 = np.matrix([[0,0],[0,1]])

def matplus(U,V):
    M = U.copy()
    for i in range(len(U)):
        for j in range(len(U[i])):
            M[i][j] += V[i][j]
    return M

def x(q,n):
    M = X
    for i in range(q):
        M = np.kron(I,M)
    for i in range(n-q-1):
        M = np.kron(M,I)
    return M

def cx(ctrl,targ,n):
    M0 = np.matrix([[1]])
    M1 = np.matrix([[1]])
    
    for i in range(n):
        if i == ctrl:
            M0 = np.kron(M0,ketbra0)
            M1 = np.kron(M1,ketbra1)
        elif i == targ:
            M0 = np.kron(M0,I)
            M1 = np.kron(M1,X)
        else:
            M0 = np.kron(M0,I)
            M1 = np.kron(M1,I)
    M = matplus(M0,M1)
    return M

def ccx(ctrl1,ctrl2,targ,n):
    
    M00 = np.matrix([[1]])
    M01 = np.matrix([[1]])
    M10 = np.matrix([[1]])
    M11 = np.matrix([[1]])
    
    for i in range(n):
        if i == ctrl1:
            M00 = np.kron(M00,ketbra0)
            M01 = np.kron(M01,ketbra0)
            M10 = np.kron(M10,ketbra1)
            M11 = np.kron(M11,ketbra1)
        elif i == ctrl2:
            M00 = np.kron(M00,ketbra0)
            M01 = np.kron(M01,ketbra1)
            M10 = np.kron(M10,ketbra0)
            M11 = np.kron(M11,ketbra1)
        elif i == targ:
            M00 = np.kron(M00,I)
            M01 = np.kron(M01,I)
            M10 = np.kron(M10,I)
            M11 = np.kron(M11,X)
        else:
            M00 = np.kron(M00,I)
            M01 = np.kron(M01,I)
            M10 = np.kron(M10,I)
            M11 = np.kron(M11,I)
    M = matplus(M00,M01)
    M = matplus(M,M10)
    M = matplus(M,M11)
    return M

def i(n):
    M = I
    for i in range(n-1):
        M = np.kron(M,I)
    return M

def list_to_unitary(gatelist,n):
    U = i(n)
    for gate in gatelist:
        if gate[0] == 'x':
            U = np.matmul(x(gate[1],n),U)
        elif gate[0] == 'cx':
            U = np.matmul(cx(gate[1],gate[2],n),U)
        elif gate[0] == 'ccx':
            U = np.matmul(ccx(gate[1],gate[2],gate[3],n),U)
    return U

def bitstring_to_sv(bitstring):
    sv = np.matrix([[1]])
    for b in bitstring:
        if b == '0':
            sv = np.kron(sv,ket0)
        elif b == '1':
            sv = np.kron(sv,ket1)
    return sv

def sv_to_bitstring(sv):
    #print(sv)
    for i in range(len(sv)):
        #print(i, sv[i,0])
        if sv[i,0] == 1:
            j = i
    n = np.log2(len(sv))
    s = '0' + str(int(n)) + 'b'
    #print(j,s)
    return format(j, s)

def generate_random_list_of_bitstrings(k,n):
    l = sample(list(np.arange(2**n)),2**k)
    l2 = []
    s = '0' + str(int(n)) + 'b'
    for i in l:
        l2.append(format(i,s))
    return l2

def test(k,n):
    bitstrings = generate_random_list_of_bitstrings(k,n)
    print(bitstrings)
    best_solution, best_solution_cost, best_solution_result, best_sorted_bits = find_solution(bitstrings,maxcost=20000,maxdepth=6)
    print(best_solution, best_solution_result, best_sorted_bits)
    
    #test:
    U = list_to_unitary(best_solution,n)
    print(U)
    result_list = [sv_to_bitstring(np.matmul(U,bitstring_to_sv(b))) for b in bitstrings]
    print(result_list)
    if result_list == best_solution_result:
        print('Test successful!')
    else:
        print('Something is wrong.')
        print(result_list)
        print(best_solution_result)
    print('\n \n')
    
    
    
            

In [3]:
test(2,4)

['0010', '0000', '0100', '0101']
[['x', 0], ['cx', 3, 2], ['x', 3], ['ccx', 1, 2, 3]] ['1011', '1001', '1101', '1111'] 1001
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]]
['1011', '1001', '1101', '1111']
Test successful!


In [4]:
for n in np.arange(2,4):
    for k in range(n):
        test(k,n)

['01']
[['x', 0]] ['11'] 11
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
['11']
Test successful!
['00', '10']
[['x', 0], ['x', 1]] ['11', '01'] 01
[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
['11', '01']
Test successful!
['110']
[['x', 2]] ['111'] 111
[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]
['111']
Test successful!
['110', '011']
[['cx', 0, 2]] ['111', '011'] 011
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]
['111', '011']
Test successful!
['111', '101', '010', '100']
[['x', 0], ['x', 2], ['ccx', 1, 2, 0], ['x', 0]] ['110', '100', '111', '101'] 100
[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]]
['110', '100', '111', '101']
Test successful!


In [5]:
for n in np.arange(2,4):
    for k in range(n):
        test(k,n)

['00']
[['x', 0], ['x', 1]] ['11'] 11
[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
['11']
Test successful!
['10', '11']
[] ['10', '11'] 10
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
['10', '11']
Test successful!
['110']
[['x', 2]] ['111'] 111
[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]
['111']
Test successful!
['110', '010']
[['x', 0], ['x', 2]] ['011', '111'] 011
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]]
['011', '111']
Test successful!
['011', '100', '000', '010']
[['cx', 0, 2], ['x', 0], ['x', 1], ['ccx', 1, 2, 0]] ['101', '111', '110', '100'] 100
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
['101', '111', '110', '100']
Test successful!
